### ISSUE TITLE
Please add support for consul watch with python api callback

### ISSUE THREAD

**Issue by deepagargit** [cablehead/python-consul#101]
Hello,

It looks consul watch support is not present in pythn-consul.

Could you please add the support for watch python API, where in a python API could be registered for callback whenever there is a change in watch.

https://www.consul.io/docs/commands/watch.html

Thanks,
Deepak

**Comment by cablehead** [comment]
Just checking, do you mean long polling consul to subscribe to updates? If so, this is the usual pattern:

```python
import consul

c = consul.Consul()

# poll a key for updates
index = None
while True:
    index, data = c.kv.get('foo', index=index)
    print data['Value']
```

If this what you were after, do you have a suggestion for how we can update the docs to make this common need more obvious?

If it's not - please reopen with an example what you'd like to accomplish. Thanks!
