### ISSUE TITLE
Specifying multiple hosts(cluster) in consul.Consul

### ISSUE THREAD

**Issue by ajays20078** [cablehead/python-consul#105]
Currently the python client connects to just one host which is a single point of failure, is there a way to specify multiple hosts/cluster while connecting to consul in consul.Consul method.

**Comment by abn** [comment]
@ajays20078 in my usecase, we rely on consul's DNS forwarding to mitigate this issue. In our environment, we have a consul agent forwarding to our BIND server and this used as the default DNS. This allows us to use _consul.service.consul_ (default case) as the host and will 'always' return a healthy host.

**Comment by abn** [comment]
Closing this issue for now as the client is not intended to handle this scenario. Ideally, this would be handled by a local consul agent to which the python client connects as opposed to a remote host. In the case of a remote host it is upto the user to handle this externally.

Feel free to reopen this if I've missed something here.
