### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by rmb938** [cablehead/python-consul#108]
@cablehead is it possible you can put a new release on Pypi? I need the added token support from the last commit and I prefer not to have a github dependency. 

Thanks!

**Comment by morpheu** [comment]
👍

**Comment by cablehead** [comment]
Sorry for the delay :/ Doing some triaging today and will cut a release in couple of hours!

**Comment by rmb938** [comment]
Awesome thanks!

**Comment by cablehead** [comment]
New release pushed to pypi as v0.6.1. includes #115 Lemme know if you see any issues.
