### ISSUE TITLE
add some contributing docs 

### ISSUE THREAD

**Issue by ArcTanSusan** [cablehead/python-consul#110]
Would be nice to have some instructions on how to setup localdev!

**Comment by cablehead** [comment]
Hi @ArcTanSusan! If you create a pull request for the docs we'd love to merge!

**Comment by mramanathan** [comment]
Hi @cablehead,

Doc should only follow .rst or markdown format is acceptable too ?

**Comment by vilobhmm** [comment]
This is an automatically generated message.

vilobhmm@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!

**Comment by cablehead** [comment]
Hi @mramanathan, atm docs are .rst, in order to work with Sphinx and PyPi

**Comment by cablehead** [comment]
Going to close this. Documentation updates will be gratefully accepted though!
