### ISSUE TITLE
catalog endpoints don't use token auth

### ISSUE THREAD

**Issue by perzizzle** [cablehead/python-consul#116]
When you establish a connection to consul (on a server that has anonymous access turned off)with:
`c = consul.Consul(host=host,  port=port, token=token, scheme='http', consistency='default', dc=dc, verify=True)`

and then try to retrieve a list of services with:
`services = c.catalog.services()`

The token isn't provided so the only services return are the consul ones. From my reading of the docs "token is an optional ACL token. If supplied it will be used by default for all requests made with this client session" this request should provide the token. I've verified the consul cluster works properly with postman doing a get on SERVER:8500/v1/catalog/services?token=MYSECURETOKEN

Am I missing something?

**Comment by cablehead** [comment]
Hi @perzizzle you're right. `token` still needs to be threaded through the Catalog endpoints

**Comment by cablehead** [comment]
Actually, does do the Catalog endpoints support `token` for reads?

https://www.consul.io/docs/agent/http/catalog.html 

The docs read like it's only used for register and deregister, in a very specialized low level way.

**Comment by cablehead** [comment]
Ah, just noticing that you have verified it does actually work...

**Comment by perzizzle** [comment]
Yeah I confirmed these endpoints use tokens. I haven't had a chance to see how much work would be required  to support this.

**Comment by racktear** [comment]
@cablehead @perzizzle I've made changes to pass tokens to catalog requests. Please check if they work.

In our setup consul is restricted by default, and doesn't show any services unless provided an API token.

**Comment by perzizzle** [comment]
@racktear @cablehead I can confirm the changes referenced above allow use of tokens with the catalog endpoints.
