### ISSUE TITLE
python-consul doesn't support python 2.6

### ISSUE THREAD

**Issue by lowzj** [cablehead/python-consul#119]
```
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import consul
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/consul/__init__.py", line 3, in <module>
    from consul.std import Consul
  File "/usr/lib/python2.6/site-packages/consul/std.py", line 5, in <module>
    from consul import base
  File "/usr/lib/python2.6/site-packages/consul/base.py", line 1914
    k: v for k, v in {
           ^
SyntaxError: invalid syntax
```

**Comment by stevenscg** [comment]
I have been battling the same issue via ansible (which requires/uses `python-consul`) for several hours just today.

This used to work just fine for me on the same installation.

When I revert python-consul back to 0.6.0 specifically, my issues are resolved:

```
[vagrant@localhost ~]$ python -V
Python 2.6.6

[vagrant@localhost ~]$ sudo pip install python-consul==0.6.0
```

**Comment by lowzj** [comment]
@stevenscg thank for your response. I open a [pull request](https://github.com/cablehead/python-consul/pull/120) to solve this issue.

**Comment by cablehead** [comment]
I've added python 2.6 to the travis test matrix: https://travis-ci.org/cablehead/python-consul/jobs/184999293 

Hopefully that'll prevent a regression like this being added again.

**Comment by cablehead** [comment]
Sweet: https://travis-ci.org/cablehead/python-consul/jobs/185000843

Thanks @lowzj !
