### ISSUE TITLE
'module' object has no attribute 'Consul' when execute script as non-root user

### ISSUE THREAD

**Issue by dj-wasabi** [cablehead/python-consul#128]
Hi,

I have an issue on CentOS 7 with python-consul 0.6.1:

```
    try:
        c = consul.Consul(host=consul_host, port=consul_port)
    except Exception, e:
        sys.exit("Failure to connect. " + str(e))
```

When I execute this script (where consul_host = localhost and consul_port = 8500) as non-root user, I get the following message:

```
Failure to connect. 'module' object has no attribute 'Consul'
```

When I'm executing the script as root, everything is fine.

What am I doing wrong?

**Comment by cablehead** [comment]
Hi there!

Is it possible to reply with the output of:

```
find $(python -c "import os, consul; print(os.path.dirname(consul.__file__))") -ls
```

**Comment by dj-wasabi** [comment]
Hi @cablehead 

Can do, but it was related to the very tight rights on `/usr/lib64/python2.7/site-packages`. They were only accessible for user root and nothing else. A `chmod 755 -R *` did the trick.

So, will close the ticket.
