### ISSUE TITLE
tcp check failure

### ISSUE THREAD

**Issue by osallou** [cablehead/python-consul#136]
Hi,
I try to add a tcp check to a process but it fails while it works well with an http check.

Code:

            consul_agent = consul.Consul(host='myconsulhost')
            consul_agent.agent.service.register('myservice',
                service_id='myservice',
                address='d6a66cc44438', # my docker container address
                port=21,
                tags=['test'])
            check = consul.Check.tcp(host= ''d6a66cc44438',
                port=21,
                interval=20)
            consul_agent.agent.check.register('my_check',
                check=check,
                service_id='myservice')

Error:

      File "/usr/local/lib/python3.4/dist-packages/python_consul-0.6.1-py3.4.egg/consul/base.py", line 877, in register
      File "/usr/local/lib/python3.4/dist-packages/python_consul-0.6.1-py3.4.egg/consul/std.py", line 40, in put
      File "/usr/local/lib/python3.4/dist-packages/python_consul-0.6.1-py3.4.egg/consul/base.py", line 157, in cb
      File "/usr/local/lib/python3.4/dist-packages/python_consul-0.6.1-py3.4.egg/consul/base.py", line 145, in __status
    consul.base.BadRequest: 400 Must provide TTL or Script and Interval!

The error is strange  as TTL/script/interval are deprecated, and it works fine with http check

If I display the check object:

    {'interval': 20, 'tcp': 'd6a66cc44438:21'}

Thanks

**Comment by cablehead** [comment]
Just checking, which version of Consul are you using? TCP checks weren't added until 0.6.. I think?

**Comment by osallou** [comment]
Ahh! I checked python lib version but not server itself. I use a docker
image from progmium, may not be the correct version..  I gonna use official
docker image which is for sure v7

Thanks

**Comment by cablehead** [comment]
All good. Report back if that sorts things out. If it is that, you could you please close out this issue?

**Comment by osallou** [comment]
Docker imzge was too old, using official docker image fixed the pb, sorry for noise.
