### ISSUE TITLE
Request / Question: environment variables should be treated as defaults instead of overrides

### ISSUE THREAD

**Issue by cornfeedhobo** [cablehead/python-consul#147]
My current use case:

I have the `consul` binary installed, and use environment variables to manage a cluster.
I also use Ansible, which in turn uses this package. With Ansible, I manage many nodes and their services, and can do this by specifying the host to operate on, but `python-consul` catches the environment variables, and overrides the settings in Ansible.

My argument is that this breaks normal expectations. I'd be happy to take this on, but figure it should be discussed first.

**Comment by cablehead** [comment]
Hi! Sorry for the delay in reply. You're right, environment variables should be overwritten if configuration is explicitly supplied. I think the only complication is the docs atm pull the defaults that will be used from the keyword args:

http://python-consul.readthedocs.io/en/latest/#consul

If we can just hard list the defaults in the docs, the code could then use say `**kwargs` for it's arguments. When an argument is not provided, it could use either the environment variable, if it's set, or the current default.

https://github.com/cablehead/python-consul/blob/master/consul/base.py#L228

Not sure if that makes sense? If it does, do you have time to take a shot at the PR?

**Comment by cornfeedhobo** [comment]
It does! My team is heads down on some stuff at the moment, but I think we will be taking a stab at a PR in the coming weeks. I'll be in touch.

**Comment by cornfeedhobo** [comment]
Unfortunately we are switching away from Consul. Sorry we didn't get a chance to get to this.
