### ISSUE TITLE
module fails if user set CONSUL_HTTP_ADDR to wrong value

### ISSUE THREAD

**Issue by EvertMDC** [cablehead/python-consul#149]
Here is the line in question, expecting a ':'
https://github.com/cablehead/python-consul/blob/master/consul/base.py#L241

When the user sets CONSUL_HTTP_ADDR to only contain the ip, we get a 
`ValueError: need more than 1 value to unpack`

If the user sets it to http://ip:8500 we get this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/consul/base.py", line 241, in __init__
    host, port = os.getenv('CONSUL_HTTP_ADDR').split(':')
ValueError: too many values to unpack
```
Problem is that when this module is used by for example Ansible, you only get the 'need more than 1 value to unpack' and you're stuck searching why.

A simple check needs to be added with a helpful error message. If I find the time I'll look into it, seems easy.

**Comment by EvertMDC** [comment]
I've created a pull request for this #150

**Comment by cablehead** [comment]
Hi! Sorry for the delay in response. I just added a note to the PR. What do you think? Want to take a stab at updating?
