### ISSUE TITLE
Using client certificates when connecting

### ISSUE THREAD

**Issue by dj-wasabi** [cablehead/python-consul#151]
Hi,

I'm curious if it is possible for using client certificates in `python-consul`. Several of my Consul instances needs a SSL certificate to access them and my script(s) will need to access these instances to get some data. I tried to look in the tests to see if there was an example and tried to find on the webs for examples, but no luck.

Kind regards,
Werner

**Comment by cablehead** [comment]
Will be fixed by #153

**Comment by cablehead** [comment]
Thanks @brocade-craig !

**Comment by brocade-craig** [comment]
Great thanks Andy

**Comment by dj-wasabi** [comment]
Thanks! @brocade-craig
