### ISSUE TITLE
How can I pull all KVs?

### ISSUE THREAD

**Issue by ligyxy** [cablehead/python-consul#155]
The similar consul python client consulate has something like `consul.kv.items()`, which returns all of the items in KVs. Is there same function in python-consul?

**Comment by cablehead** [comment]
Hi @ligyxy.

`python-consul` goal is to only expose Consul's api and features as accurately as possible. The thought then is other projects can layer on conveniences that make sense for them.

You can pull all kv items from Consul with:

```
import consul
c = consul.Consul()
index, data = c.kv.get("", recurse=True)
```

**Comment by cablehead** [comment]
You can then flip all the kv entries to a python dict with:

```
items = dict((x['Key'], x['Value']) for x in data)
```
