### ISSUE TITLE
agent.service.deregister failed when service id contains '#'

### ISSUE THREAD

**Issue by CocaCola183** [cablehead/python-consul#156]
test on macOS 10.12.2 and centos 6.5(final)

* consul 0.7.5
* python: 2.7.13
* python-consul: 0.7.0

for example:

```python
result = consul_client.agent.service.deregister("app#127.0.0.1#3000")
```

`result` is true, bug deregister failed.

consul log is :

```
2017/07/08 09:56:48 [WARN] agent: Failed to deregister service "app": Service does not exist
```

**Comment by cablehead** [comment]
`c.health.service("app#127.0.0.1#3000")` is also an issue

**Comment by trdcaz** [comment]
Because fragments were not sent in HTTP request messages, consul received `app` instead of `app#127.0.0.1#3000`. So it's better to quote using [Percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding) before send directly.

Sample code below:

[https://github.com/cablehead/python-consul/blob/master/consul/base.py#L58](https://github.com/cablehead/python-consul/blob/master/consul/base.py#L58)

```python
from six.move import urllib_parse

url = urllib_parse.quote(url, safe='/:')
ret = {'http': url, 'interval': interval}
```

**Comment by abn** [comment]
I have a fix based on @trdcaz 's comment. However, note that this does introduce the possibility that other RFC "safe" characters may need to be added to the safe list later on. However, I cannot think of a case off the top of my head.

In addition, this issue also raises another concern in that the `service.deregister` is returning `True`. However, this is sort of expected as this is the behaviour of the server itself. Considering we intend to provide a lightweight library, error checking can be left as an exercise for application developers - but I do think we need to document this behaviour if not done so already. 
```
$ curl -v -X PUT -d '{"name": "foobar"}' 'http://localhost:8500/v1/agent/service/register'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8500 (#0)
> PUT /v1/agent/service/register HTTP/1.1
> Host: localhost:8500
> User-Agent: curl/7.53.1
> Accept: */*
> Content-Length: 18
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 18 out of 18 bytes
< HTTP/1.1 200 OK
< Date: Mon, 31 Jul 2017 07:10:28 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact

$ curl -v -X PUT 'http://127.0.0.1:8500/v1/health/service/deregister/foobar'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8500 (#0)
> PUT /v1/health/service/deregister/foobar HTTP/1.1
> Host: 127.0.0.1:8500
> User-Agent: curl/7.53.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Consul-Index: 9
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 0
< Date: Mon, 31 Jul 2017 07:11:04 GMT
< Content-Length: 2
< 
* Connection #0 to host 127.0.0.1 left intact
[]

$ curl -v -X PUT 'http://127.0.0.1:8500/v1/health/service/deregister/foobar'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8500 (#0)
> PUT /v1/health/service/deregister/foobar HTTP/1.1
> Host: 127.0.0.1:8500
> User-Agent: curl/7.53.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Consul-Index: 9
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 0
< Date: Mon, 31 Jul 2017 07:11:10 GMT
< Content-Length: 2
< 
* Connection #0 to host 127.0.0.1 left intact
```
