### ISSUE TITLE
Add ability to use SSL

### ISSUE THREAD

**Issue by pete0emerson** [cablehead/python-consul#16]
Add the ability to use SSL to encrypt requests traffic if consul is fronted by an SSL offloading load balancer.

**Comment by cablehead** [comment]
I think this would be straight forward? Just need to allow scheme to be customizable.

**Comment by pete0emerson** [comment]
I submitted a pull request. No tests written, but in my testing it works. Probably a bunch of different ways to skin the cat, so if you think there's a better way that fits your model, go nuts!

Pete

**Comment by cablehead** [comment]
Thanks Pete, appreciate the patch. Yeah, I can't think of a practical way to test this one.
