### ISSUE TITLE
Handle additional 4xx HTTP status codes

### ISSUE THREAD

**Issue by bagerard** [cablehead/python-consul#186]
while developing I noticed the following bug as well (#179), and it made the service.deregister method returning False without any additional information.
By debugging the code I could see that consul actually returned a 405 (method not allowed) that isn't caught in CB.__status.

Even if #179 will be fixed I thought it could be useful to handle all the 4xx status code (in a generic manner) in CB.__status. I'll submit a PR shortly

**Comment by bra-fsn** [comment]
+1, it's very annoying. While experimenting with the server/client I've started a transaction with 100 operations, but all I got is a ValueError: No JSON object could be decoded, so -instead of reading the exception and the stacktrace carefully- I thought some bad data got into the pipeline.
