### ISSUE TITLE
ttl_pass should be put not get

### ISSUE THREAD

**Issue by Parag08** [cablehead/python-consul#197]
line 1015 in base.py should be:
"""
                return self.agent.http.put(
                    CB.bool(),
                    '/v1/agent/check/pass/%s' % check_id,
                    params=params)
"""

instead of
"""
 return self.agent.http.get(
                    CB.bool(),
                    '/v1/agent/check/pass/%s' % check_id,
                    params=params)
"""

**Comment by cablehead** [comment]
Should be fixed by #182
