### ISSUE TITLE
Can't use behind proxy

### ISSUE THREAD

**Issue by zeratulayuris** [cablehead/python-consul#208]
I'm behind proxy and have proxy settings exported - my app needs it to work, as it's making request to outside services. But this makes requests, which is used by python-consul too, to grab this settings and send requests to 127.0.0.1 via proxy. Clearly it fails.
Question is: how can I force python-consul to make requests to not use proxy?

**Comment by asteven** [comment]
Depending on the client you are using you can set the NO_PROXY environment variable.

I have the following set on most of my hosts
```
export no_proxy=localhost,127.0.0.1,.service.consul
```
This works fine with curl and friends, have not yet tested with python-consul or requests in general.
But it seems this should work at least with the requests based (std.py) implementation. See e.g. https://stackoverflow.com/questions/28521535/requests-how-to-disable-bypass-proxy

**Comment by matusvalo** [comment]
@asteven is right. Since python-consul is basically wrapper around Consul HTTP interface, controlling proxy usage can be done using http_proxy, https_proxy and no_proxy environment variables - see:

https://wiki.archlinux.org/index.php/proxy_settings

**Comment by matusvalo** [comment]
Documentation update was committed to the project. Now this should be clear from docs.
