### ISSUE TITLE
consul 1.1.0 has deprecated 'script' parameter

### ISSUE THREAD

**Issue by shantanugadgil** [cablehead/python-consul#212]
Hi,

Consul 1.1.0 has permanently removed the script parameter for script based health checks.
ref: https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#user-content-110-may-11-2018

Any plans to enhance to cater to this?

BTW, 
Thanks for the great work on updating this to support Consul 1.0.x.

**Comment by nvtkaszpir** [comment]
Looks like this effectively also breaks ansible consul module.

**Comment by matusvalo** [comment]
The fix is easy, we need to change to
```python
return {'args': script, 'interval': interval}
```
in
https://github.com/cablehead/python-consul/blob/b91a692e6858724bcc531925cadacf558cb9e446/consul/base.py#L56

This can break compatibility with Consul before 1.0.1 version. Moreover, this breaks API since `consul.Check.script` will accept list instead of string.

The question is whether we are fine with this breaking change. @cablehead  what do you think?

**Comment by nvtkaszpir** [comment]
I believe we can define different behaviour based on consul version detected?

**Comment by pathcl** [comment]
Hello,

I requested a PR for this. Its already here:

https://github.com/cablehead/python-consul/pull/216

Kind regads,

**Comment by pathcl** [comment]
I'll be working on this issue this weekend just to have fun. Stay tuned :)

**Comment by pathcl** [comment]
@shantanugadgil if you want to try a quick fix go to my fork. https://github.com/pathcl/python-consul

It will take my a little bit more time than I thought since I also want to clean up some code.

Best,

**Comment by cablehead** [comment]
Thanks for the PR @pathcl. Looking at what's needed to maintain backwards compatibility, kinda makes me think we should just make this a breaking change :). python-consul is versioned, so people can just run the version of python-consul that matches their version of consul.

@matusvalo does that match your thinking too?

**Comment by cablehead** [comment]
@matusvalo actually, we could shlex.split the arg passed to Check.script is it's not a list?

**Comment by cablehead** [comment]
Perhaps #218? Getting a bunch of unrelated test failures locally. Still need to investigate.

**Comment by cablehead** [comment]
Tests are passing now. Does anyone have any objections to this approach?

**Comment by shantanugadgil** [comment]
hi @pathcl thanks, I will need some messing around in our build system.
I hope I'll be able to give this a try soon, backed up on a few other things for now.

thanks @cablehead for this module.
Should I just wait for the 1.1.0 release ? I will be a few days before I can try this.

Cheers,
Shantanu

**Comment by matusvalo** [comment]
@cablehead I agree with you that approach when checks against Consul API are executed every creation of consul object. For me if we want to keep backward compatibility we have two options:
1. create separate API for new call (`script_args()`)
2. control backward compatibility with environment variables - e.g. if user wants to use library supporting older consul, he should export special variable e.g. CONSUL_OLD etc.

But both options are difficult to maintain, test etc. so If nobody is againstm I prefer to stick with newest consul and document it properly that anyone can use proper version of python-consul when wants to support older Consul versions.

**Comment by cablehead** [comment]
I've merged #218
