### ISSUE TITLE
Import Error six.move.urllib

### ISSUE THREAD

**Issue by AndreLobato** [cablehead/python-consul#23]
Hi there, after install consul 

import consul
then...
.../python2.7/site-packages/consul/__init__.py in <module>()
__version__ = '0.3.10'
from consul.std import Consul

.../python2.7/site-packages/consul/std.py in <module>()
from six.moves import urllib

ImportError: cannot import name urllib

**Comment by AndreLobato** [comment]
Never mind just using a old version of six (1.3.0) on a newer version (1.9.0) the error does not occurs.

Thanks

**Comment by line2sun** [comment]
I have the same issue, but with the `1.10` version of `six` lib
