### ISSUE TITLE
Consul.Session create is not implement Ephemeral Keys

### ISSUE THREAD

**Issue by yanypunix** [cablehead/python-consul#26]
curl -X PUT -d '{"behavior":"delete"}' localhost:8500/v1/session/create
{"ID":"acf52e93-6b45-6297-6425-bb97a340b144"}

>>> import consul
>>> c=consul.Consul()
>>> c.session.create(name='aaa',behavior='delete')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: create() got an unexpected keyword argument 'behavior'

python-consul:
    class Session(object):
        def __init__(self, agent):
            self.agent = agent
            self.check = Consul.Health.Check(agent)

        def create(
                self,
                name=None,
                node=None,
                checks=None,
                lock_delay=15,
                dc=None):

the 'behavior' is lack in create()

**Comment by cablehead** [comment]
Thanks for the prod @yanypunix 

I've added the behavior and ttl params for session.create, and added the new session.renew endpoint.

I've pushed up and release as v0.3.12 -- could you upgrade and give it a whirl?!
