### ISSUE TITLE
agent.service.register doesn't take an IP address

### ISSUE THREAD

**Issue by dpnova** [cablehead/python-consul#31]
As per the docs here: https://www.consul.io/docs/agent/http/agent.html#agent_service_register

Shouldn't agent.service.register take an IP address?

Perhaps I'm being a consul noob, but it seems hard to get a service with an IP address using the agent interface instead of the catalog interface...

**Comment by chadlung** [comment]
I'm wondering about this as well as I'm writing an article on python-consul and Consul. Looking at Consulate it appears they recently fixed this oversight: https://github.com/gmr/consulate/commit/4d02db190b619724369dff2ae9229701a007df15

The Consul docs state it would use the address of the agent but I don't see that reflected in the output when I dump all the services:

```
{
    u'consul': {
        u'Address': u'',
        u'Port': 8300,
        u'ID': u'consul',
        u'Service': u'consul',
        u'Tags': [
            
        ]
    },
    u'my_http_service_1': {
        u'Address': u'',
        u'Port': 80,
        u'ID': u'my_http_service_1',
        u'Service': u'my_http_service',
        u'Tags': [
            u'mytag1',
            u'mytag2'
        ]
    }
}
```

**Comment by cablehead** [comment]
Looks like the ability to set an address for a service was added for Consul 0.5.0

https://github.com/hashicorp/consul/blob/master/CHANGELOG.md

**Comment by cablehead** [comment]
Will at support for this soon. Sunday at the latest.

**Comment by cablehead** [comment]
Apologies for the delay. I've tagged and pushed up as 0.3.17

**Comment by chadlung** [comment]
Excellent, thanks for the hard work!
