### ISSUE TITLE
Add ServiceID and SerivceName fields to agent.check.register

### ISSUE THREAD

**Issue by cruatta** [cablehead/python-consul#36]
A ServiceID and ServiceName can be specified when registering a check in consul. They are less obvious in the API docs (I plan on making a PR to update the docs) but here is an example of it working.

```
bash-4.1# cat service.json
{
  "ID": "redis1",
  "Name": "redis"
}
bash-4.1# cat check.json
{
  "ID": "mem",
  "Name": "Memory utilization",
  "Notes": "Ensure we don't oversubscribe memory",
  "Script": "/usr/local/bin/check_mem.py",
  "Interval": "10s",
  "ServiceName": "redis",
  "ServiceID": "redis1"
}
bash-4.1# curl -X PUT -H 'Content-Type: application/json' -d @service.json 172.17.0.21:8500/v1/agent/service/register
bash-4.1# curl -X PUT -H 'Content-Type: application/json' -d @check.json 172.17.0.21:8500/v1/agent/check/register
bash-4.1# curl 172.17.0.21:8500/v1/agent/checks
{"mem":{"Node":"node4","CheckID":"mem","Name":"Memory utilization","Status":"critical","Notes":"Ensure we don't oversubscribe memory","Output":"/bin/bash: /usr/local/bin/check_mem.py: No such file or directory\n","ServiceID":"redis1","ServiceName":"redis"}}
```
If a ServiceID is provided, a ServiceName can optionally be provided. If the ServiceName is provided without the ServiceID, it is not registered in the check.

**Comment by cablehead** [comment]
Interesting. I can't see them *at all* in the docs, haha.

https://www.consul.io/docs/agent/http/agent.html#agent_check_register

Is there somewhere else this feature is mentioned?

**Comment by cruatta** [comment]
Looks like my PR was merged. The docs should be updated now.
