### ISSUE TITLE
Unclosed connector Exception in consul.aio

### ISSUE THREAD

**Issue by ffix** [cablehead/python-consul#47]
Thee is simple script with consul.aio:
```
import asyncio
import consul.aio

loop = asyncio.get_event_loop()
c = consul.aio.Consul()


@asyncio.coroutine
def go():
    session = yield from c.session.create(ttl=20)
    assert session

    response = yield from c.session.destroy(session)
    assert session


if __name__ == '__main__':
    loop.run_until_complete(go())
```

If I run it I'll get an exception:
```
Unclosed connector
connector: <aiohttp.connector.TCPConnector object at 0x7f9dc0121cc0>
Exception ignored in: 
```
Python 3.4.3
aiohttp 0.16.3
python-consul 0.3.19

**Comment by cablehead** [comment]
Want to have a shot a providing a pull request? I don't personally use asyncio.

@jettify might be able to help too...

**Comment by jettify** [comment]
New asyncio/aiohttp more strict to unclosed connections. We need to call ```aio.HTTPClient._connector.close()``` to close http connections.

**Comment by jettify** [comment]
I'll do PR

**Comment by ffix** [comment]
I've done some monkey patching few days ago:
```
class HTTPClient(consul.aio.HTTPClient):
    def __del__(self):
        self._connector.close()
```
but there is still exception with ResourceWarning: unclosed <socket object>.

**Comment by jettify** [comment]
Cool, I've forgotten about ``__del__`` method. I'll add this to my PR too.

**Comment by cablehead** [comment]
Ah, I might have merged too soon. Is there an additional change to come?

**Comment by jettify** [comment]
yes, I'll add ``__del__`` method with ``ResourceWarning``, I need like more 5-10 min

**Comment by cablehead** [comment]
:+1:

**Comment by cablehead** [comment]
Pushed to Pypi as v0.3.20

**Comment by ffix** [comment]
Thank you for the fix but ResourceWarning is still here:
```
$ python -Wdefault /tmp/1                                                                                                                                                     
Exception ignored in: sys:1: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('127.0.0.1', 44245), raddr=('127.0.0.1', 8500)>

```

**Comment by kshpytsya** [comment]
```
loop.run_until_complete(c.http._session.close())
```
before
```
loop.close()
```
seems to help.
