### ISSUE TITLE
API Docs partially deleted

### ISSUE THREAD

**Issue by sfncook** [cablehead/python-consul#54]
The API documentation were recently partially deleted.  any chance of getting those back?

http://python-consul.readthedocs.org/en/latest/#api-documentation

**Comment by cablehead** [comment]
Thanks for the heads up. Looks like there was a build issue at readthedocs. I've wiped and rebuilt. It should look better now?

**Comment by sfncook** [comment]
Awesome! Yeah fixed.  Thanks!
