### ISSUE TITLE
Consul.Catalog.Service w/ tag specified throws error

### ISSUE THREAD

**Issue by sfncook** [cablehead/python-consul#55]
Sorry I don't have time to dig into this and help resolve it right now.  Will try to circle around and get back to it, but I wanted to log a potential issue.  Getting potentially unwaranted error message when I try to query Consul (using python-consul, of course) for a service with a tag specifier.

This code:
    def simple_passthru_consul_catalog_service(self, service_name, tag):
        consul_ = consul.Consul('consul')
        print consul_.catalog.services()
        return consul_.catalog.service(service="redis-holt-overflow", tag="master")

Produces this output and error message:
('44', {u'consul-8301': [u'udp'], u'consul-8300': [], u'consul-8302': [u'udp'], u'consul': [], u'redis-holt-overflow': [u'master', u'slave'], u'consul-8400': [], u'consul-53': [u'udp'], u'consul-8500': []})

Attempt #9 of 60 failed.
ERROR:root:Consul connection problem - Exception:No JSON object could be decoded
Traceback (most recent call last):
  File "/bin/python/consul_def.py", line 72, in get_consul_service_with_name_withfunc
    [index, json_objs] = consul_catalog_service_func("redis-holt-overflow", "master")
  File "/bin/python/consul_def.py", line 59, in simple_passthru_consul_catalog_service
    return consul_.catalog.service("redis-holt-overflow", "master")
  File "/usr/local/lib/python2.7/dist-packages/consul/base.py", line 1079, in service
    '/v1/catalog/service/%s' % service, params=params)
  File "/usr/local/lib/python2.7/dist-packages/consul/std.py", line 30, in get
    return callback(self.response(requests.get(uri)))
  File "/usr/local/lib/python2.7/dist-packages/consul/base.py", line 119, in cb
    data = json.loads(response.body)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

For reference here is the curl response directly from Consul:
curl -s localhost:8500/v1/catalog/service/redis-holt-overflow

[{"Node":"consul","Address":"192.168.59.103","ServiceID":"fearbattle-lm:redis.m:6380","ServiceName":"redis-holt-overflow","ServiceTags":["master"],"ServiceAddress":"","ServicePort":6380},{"Node":"consul","Address":"192.168.59.103","ServiceID":"fearbattle-lm:redis.s:6381","ServiceName":"redis-holt-overflow","ServiceTags":["slave"],"ServiceAddress":"","ServicePort":6381}]

Again, my apologies for not working out a solution or digging deeper.  Under pressure right now.

**Comment by sfncook** [comment]
I should also note that the exception traceback listed above is generated from a calling method where the exception is caught and logged - hence a few extra lines with my logging formatting.  e.g. "Attempty #9 of 60 failed..."

**Comment by cablehead** [comment]
Hi!

Is it possible to print out response.body before:

```
File "/usr/local/lib/python2.7/dist-packages/consul/base.py", line 119, in cb
data = json.loads(response.body)
```

in consul/base.py?

**Comment by sfncook** [comment]
I would be happy to try but I'm really not familiar with how to run the code without the PIP package.  Again, it's something I could figure out if I had a little more time.

**Comment by abn** [comment]
@sfncook  looks like the culprit here is
```
File "/bin/python/consul_def.py", line 59, in simple_passthru_consul_catalog_service
return consul_.catalog.service("redis-holt-overflow", "master")
```

The signature for _Catalog.service_ method is as follows:
```py
        def service(
                self,
                service,
                index=None,
                wait=None,
                tag=None,
                consistency=None,
                dc=None):
```

Your second argument `master` is being used as index (which is expected to be the Consul Index). Try leaving that as None instead.

Closing this issue as this does not appear to be a bug in the code. Feel free to re-open if this is not accurate.
