### ISSUE TITLE
Allow certificates signed by custom CA

### ISSUE THREAD

**Issue by sduthil** [cablehead/python-consul#57]
Hi,

We'd like to use Consul over HTTPS using a self-signed certificate that we trust.

The only way we found that works is using the environment variable REQUESTS_CA_BUNDLE. But this is global for the whole process and we use requests for other HTTP queries where the custom CA is not necessarily wanted.

Requests provides a `verify` argument for its session/requests where we can give a custom CA bundle, but python-consul does not.

We may write the pull request, but first : would you accept the feature ?
Also, should we allow disabling certificate verification completely ?

**Comment by jgadling** [comment]
We need this feature too, pull request here: https://github.com/cablehead/python-consul/pull/62

**Comment by sduthil** [comment]
Fixed by #62
