### ISSUE TITLE
Watch support?

### ISSUE THREAD

**Issue by harlowja** [cablehead/python-consul#71]
It doesn't appear watches are currently supported, having them would be great! (or letting me know they exist); something akin to https://github.com/python-zk/kazoo/blob/master/kazoo/recipe/watchers.py could be a pattern that is emulated.

**Comment by cablehead** [comment]
Hi @harlowja. The usual pattern is to make a blocking call using the index parameter. This will return when new data has been added. Here's an example using the Vanilla Python async client (https://github.com/cablehead/vanilla.consul)

```python
import vanilla
import pprint

h = vanilla.Hub()

# simulate a process that periodically updates a key value
@h.spawn
def _():
    c = h.consul()
    value = 0
    while True:
        h.sleep(3000)
        value = value + 1
        c.kv.put("foo", str(value)).recv()


# watch a key value
c = h.consul()
index = None
while True:
    index, data = c.kv.get("foo", index=index).recv()
    print "UPDATE:"
    pprint.pprint(data)
    print
```

**Comment by cablehead** [comment]
Does this help?

**Comment by ccl0326** [comment]
We also need this feature.As the usual pattern,if we need some interface like Health.service.We need copy the code and finish this same logic with the pattern.

**Comment by harlowja** [comment]
Perhaps start a patterns folder and share these common pieces of code there?

On Tuesday, October 20, 2015, Chen Chenglong <notifications@github.com>
wrote:

> We also need this feature.As the usual pattern,if we need some interface
> like Health.service.We need copy the code and finish this same logic with
> the pattern.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cablehead/python-consul/issues/71#issuecomment-149481471>
> .
>


-- 
--
facebook.com/jshharlow <http://www.facebook.com/jshharlow>
flickr.com/jshharlow
YIM: jshharlow

**Comment by cablehead** [comment]
There's an example uses section in the docs:

http://python-consul.readthedocs.org/en/latest/#example-uses

Do you think it'd work to add these common patterns there?

**Comment by harlowja** [comment]
I was thinking under https://github.com/cablehead/python-consul/tree/master/consul/patterns 

Examples are great, and such, but I've always preferred having in-code-tree patterns like what kazoo also provides (as recipes): https://github.com/python-zk/kazoo/tree/master/kazoo/recipe

Which itself come from http://curator.apache.org/curator-recipes/index.html and others at https://github.com/Netflix/curator/wiki/Recipes

**Comment by pipozzz** [comment]
Can you help me with watching ?
```
import consul.tornado
import tornado


class Config(object):
    def __init__(self):
        self.foo = None
        loop.add_callback(self.watch)

    @tornado.gen.coroutine
    def watch(self):
        c = consul.tornado.Consul()

        # asynchronously poll for updates
        index = None
        while True:
            index, data = yield c.catalog.nodes(index=index)
            print("Index: {}".format(index))
            print("Data: {}".format(data))

if __name__ == "__main__":
    loop = tornado.ioloop.IOLoop()
    loop.make_current()
    c = Config()
    loop.run_sync(c.watch)
```


what am I doing wrong ? I'm still getting Timeouts (tornado.httpclient.HTTPError: HTTP 599: Timeout during request)
Thanks

**Comment by fruch** [comment]
watch seems to be a first class action in consul.io,  I think just having a recipe to achieve something similar is not enough. (not that I'm saying it's easy to implement for various types of clients)

**Comment by fruch** [comment]
after reading the documentation again, I take that back...  watch isn't first class in the http api

**Comment by cablehead** [comment]
Hi @pipozzz.. were you able to get this to work? If a change doesn't occur before the timeout that's configured with your http client, then yeah, it'll timeout. It's normal to need to reestablish the watch from the long poll, if it returns before there's a change. Just keep the current index value that you have.

**Comment by cablehead** [comment]
Going to close this. Totally agree more examples and documentation would be helpful. If anyone sends through a PR for them, we'll look to get them merged.
