### ISSUE TITLE
Agent.service.register() ignores token?

### ISSUE THREAD

**Issue by hynek** [cablehead/python-consul#73]
I might be doing something stupid, but I’m starting out with Consul and I bind a token using `c = Consul(token="my-token")`, can verify it’s on `c.agent.token`, but it’s not sent when I try to register a service.  Which leads to a local success but entries like 

    2015/10/21 20:43:12 [WARN] agent: Service 'metrics.test' registration blocked by ACLs

in my consul logs.  So the data never reaches my cluster.

Glancing over https://github.com/cablehead/python-consul/blob/master/consul/base.py#L593-L655 looks like it completely ignores the token?  Or is it me?

**Comment by cablehead** [comment]
Thanks for catching this.

Hrm, I can't work out how ACLs for services are supposed to work. I quickly add a passthrough for c.agent.service.register for token.. but in tests/test_std.py:test_acl_implicit_token_use i added a quick check expecting service creation to be denied, unless using a valid token, but I couldn't get consul to deny service creation.

Could you take a shot at adding a test to that function to demonstrate that tokens are working as expected?

**Comment by hynek** [comment]
Yeah as I wrote, it works *locally* but the services  aren't federated to the cluster with the log error I pasted.  That behavior also confused the crap out of me. :)

So all you can test for is to endure, that there's a token…

**Comment by cablehead** [comment]
Ah gotcha. Thanks for the clarification. KK, I think I can see a way to test it now.

**Comment by cablehead** [comment]
token should work with agent.service.register and agent.check.register now

pushed as v0.4.7

**Comment by hynek** [comment]
Thank you, it works now indeed!
