### ISSUE TITLE
Problem with installing python-consul package 0.4.7 on OSX

### ISSUE THREAD

**Issue by vilobhmm** [cablehead/python-consul#76]
Best match: python-consul 0.4.7
Downloading https://pypi.python.org/packages/source/p/python-consul/python-consul-0.4.7.tar.gz#md5=e695b8897d1e84eb23a8d9d20a6d47da
Processing python-consul-0.4.7.tar.gz
Writing /var/folders/tw/wh1w60j512j7lks_1nhtmq2r002js8/T/easy_install-7x5eun/python-consul-0.4.7/setup.cfg
Running python-consul-0.4.7/setup.py -q bdist_egg --dist-dir /var/folders/tw/wh1w60j512j7lks_1nhtmq2r002js8/T/easy_install-7x5eun/python-consul-0.4.7/egg-dist-tmp-I8VvED
  File "build/bdist.macosx-10.10-intel/egg/consul/aio.py", line 41
    resp = yield from aiohttp.request(method, uri,
                    ^
SyntaxError: invalid syntax

zip_safe flag not set; analyzing archive contents...
Copying python_consul-0.4.7-py2.7.egg to /Users/vilobhmm/source/mitaka/add-consul-driver/tooz/.venv/lib/python2.7/site-packages
Adding python-consul 0.4.7 to easy-install.pth file

**Comment by vilobhmm** [comment]
Steps to reproduce 

1. Checkout tooz https://github.com/openstack/tooz

2 .create virtualenv

3 run python setup.py develop

**Comment by cablehead** [comment]
Is this something you're still seeing?

**Comment by abn** [comment]
closing this one as no response from reporter.
