### ISSUE TITLE
Missing version requirement on requests

### ISSUE THREAD

**Issue by elessard1** [cablehead/python-consul#78]
Hello,

just had this problem today, although this might be a bit of a odd case, but I was in an environment with an old version of request (0.12) and tried to used python-consul from it, but it was failing with the following error:

```
  File "/usr/lib/python2.7/dist-packages/consul/base.py", line 1642, in create
    callback, '/v1/acl/create', params=params, data=data)
  File "/usr/lib/python2.7/dist-packages/consul/std.py", line 39, in put
    self.session.put(uri, data=data, verify=self.verify)))
  File "/usr/lib/python2.7/dist-packages/consul/std.py", line 23, in response
    response.status_code, response.headers, response.text)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 809, in text
    content = str(self.content, encoding, errors='replace')
TypeError: unicode() argument 2 must be string, not None
```

In the requirements.txt of python-consul, there is no version specified for requests. I don't know which is the lowest version of requests which works with python-consul, but I know it's greater than 0.12. If this could be updated, this would be great.

**Comment by cablehead** [comment]
Ah, great observation. I don't suppose you're able to determine which version is the first good one?

**Comment by cablehead** [comment]
If not, I'll try and set aside some time myself to step through with virtualenv to try and find it.

**Comment by elessard1** [comment]
Nope I don't know which version if the first good one. I only know that:

- it doesn't work with 0.12
- it seems to work fine with 2.0 or later

**Comment by cablehead** [comment]
I'll take a stab at pinning it to _something_

**Comment by cablehead** [comment]
https://github.com/cablehead/python-consul/commit/7c34c249f15fc6b57c2e7aa0b537688fd75233b4#diff-b4ef698db8ca845e5845c4618278f29aL1

Reopen if you've more thoughts..
