### ISSUE TITLE
Best way to Lookup for a service

### ISSUE THREAD

**Issue by milind-git** [cablehead/python-consul#84]
Hello, 
I would like to do service lookup ( I have only service id, service name and one tag with me).
##### Q : Is there a way in Python-Consul ( or proposed) to get service by providing service_id alone or by providing service_name and tag value together?
As of now , in Python-Consul, following methods support lookup of service(s):
##### consul.catalog.service(service)     -->  _Not sure what is the input here, can I pass service as { "ID" : 123, "Service" : "servicename" }_ 

Thanks.

**Comment by abn** [comment]
This should do the trick to look up services given name and tag.
```py
consul.catalog.service(service=service_name, tag=tag)
```

For, fetching services with a given _ServiceID_, you might be better off querying all services or by name first, then filtering based on _ServiceID_ in your application.

**Comment by milind-git** [comment]
Thanks, I will give it a try.

**Comment by milind-git** [comment]
Thanks a lot abn, it worked.

**Comment by cfrelet** [comment]
Hi,

Can Tag be a list of Tag here?
I seem to be able to input only a string.

cat = c.catalog.service(service = "worker", tag = 'HK') => OK

cat = c.catalog.service(service = "worker", tag = ['HK','SG']) => KO
