### ISSUE TITLE
Update the a particular tag from Service tags

### ISSUE THREAD

**Issue by milind-git** [cablehead/python-consul#88]
Hello,
Is there a way to update a particular tag of already registered service? I know re-registering the service would work but then that's a pain and unsafe of losing out original service_id etc.. I just want to update a tag or list of tags of registered services ( I would query them by service_name or so).
Thanks.

**Comment by cablehead** [comment]
Hi @milind-git. This is more of a direct Consul question. I'm pretty sure Consul only offers `register` and `deregister` capabilities. 

<img width="707" alt="screen shot 2016-02-07 at 10 07 21 am" src="https://cloud.githubusercontent.com/assets/1394/12874145/f13abbb8-cd82-11e5-8ce8-bb831f5e69ef.png">

I could be mistaken though? If I am, reopen, and I'll add support!
