### ISSUE TITLE
Need to make jsonified input as optional

### ISSUE THREAD

**Issue by vilobhmm** [cablehead/python-consul#89]
There are various places in code for example 

https://github.com/cablehead/python-consul/blob/master/consul/base.py#L521
https://github.com/cablehead/python-consul/blob/master/consul/base.py#L535

which does a json.loads as a result of which things can break please check logs below

http://logs.openstack.org/62/245362/33/check/gate-tooz-tox-py27-consul/d0a069a/testr_results.html.gz

Do we really need a json.loads here can we make it optional ?

Change is here https://review.openstack.org/#/c/245362/33/tooz/drivers/consul.py

I am available on #openstack-state-management with username vilobhmm for more details.

**Comment by cablehead** [comment]
Hi @vilobhmm. Do you know why Consul isn't returning valid Json for these tests? It does under normal conditions: https://www.consul.io/docs/agent/http/agent.html#agent_self. Is there an error condition here which we should catch in python-consul?

**Comment by vilobhmm** [comment]
@cablehead : IMHO either consul is not returning valid JSON or python-consul is not able to parse it and send it back to the tests.

**Comment by harlowja** [comment]
Perhaps what u want is a way to see the invalid (or maybe invalid?) json?

A temporary way to do this (do not use this in production...)

```
>>> import json
>>> _old_json_loads = json.loads
>>> def _dumping_loads(s, **kwargs):
...    print("Try to read '%s' as json" % s)
...    return _old_json_loads(s, **kwargs)
>>> 
>>> json.loads = _dumping_loads
```

**Comment by cablehead** [comment]
@vilobhmm no need to leave it to opinion. Is it possible to print out what's being returned?

**Comment by vilobhmm** [comment]
@cablehead : trying to dump the output. Will paste it when here when the tests r done so that we have an idea whats going wrong. You can see the changes here https://review.openstack.org/#/c/245362/33

**Comment by cablehead** [comment]
Awesome, thanks!

**Comment by abn** [comment]
@vilobhmm any updates on this one?

According to the consul [HTTP API Docs](https://www.consul.io/docs/agent/http.html), all valid responses will be JSON.

> By default, the output of all HTTP API requests is minimized JSON. If the client passes pretty on the query string, formatted JSON will be returned.

Looking at the logs, it seems to me that consul returning an error code that is, possibly, not handled by python-consul. There have been a few bug fixes around this on master. The best way to debug this, as suggested above, would be to capture the raw response or the response body.

**Comment by cablehead** [comment]
Going to close this one. Please reopen though @vilobhmm if there's still an issue that you are seeing.
