### ISSUE TITLE
Consul  watch Python API? 

### ISSUE THREAD

**Issue by 467754239** [cablehead/python-consul#95]
I didn't find where?

**Comment by cablehead** [comment]
Just checking, do you mean long polling consul to subscribe to updates? If so, this is the usual pattern:

```
import consul

c = consul.Consul()

# poll a key for updates
index = None
while True:
    index, data = c.kv.get('foo', index=index)
    print data['Value']
```

**Comment by cablehead** [comment]
Going to close this. Just reopen if I didn't answer your question.
