### ISSUE TITLE
/v1/health/state/any long response

### ISSUE THREAD

**Issue by 123BLiN** [cablehead/python-consul#96]
Time of method consul.Health.state('any') is much more longer than native HTTP query (about 4 times longer, 2 to 7 sec) with 50+ services. We have latest version from pip.

**Comment by maxnasonov** [comment]
Hi @123BLiN/Roman. It might be fixed with #97

**Comment by abn** [comment]
@123BLiN can you try with master?

**Comment by 123BLiN** [comment]
Hi @abn ! We have been using #97  fix for a month with success, I see you have merged it to master, so all should be good now. Thanks a lot! Closing.
